apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: setu
resources:
  - ../../base
patches:
  - path: patch-production-config.yaml
  - path: patch-production-resources.yaml
  - path: patch-production-tracing.yaml
