-- SETU Kafka event backbone: transactional Postgres outbox.
-- The database transaction that changes a business row also inserts its event
-- into this table. A worker later publishes the event to Kafka and marks it
-- published. This avoids the dual-write failure mode of "DB commit + Kafka
-- publish" being performed as two unrelated operations.

create table if not exists public.setu_event_outbox (
  id              bigint generated by default as identity primary key,
  event_id        uuid not null default gen_random_uuid() unique,
  event_type      text not null,
  aggregate_type  text not null,
  aggregate_id    text,
  payload         jsonb not null,
  attempts        integer not null default 0,
  created_at      timestamptz not null default now(),
  published_at    timestamptz,
  last_error      text
);

create index if not exists idx_setu_event_outbox_unpublished
  on public.setu_event_outbox (created_at)
  where published_at is null;

create index if not exists idx_setu_event_outbox_aggregate
  on public.setu_event_outbox (aggregate_type, aggregate_id, created_at desc);

alter table public.setu_event_outbox enable row level security;
drop policy if exists setu_event_outbox_service_only on public.setu_event_outbox;
create policy setu_event_outbox_service_only
  on public.setu_event_outbox for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create or replace function public.setu_enqueue_kafka_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  aggregate_type text;
  aggregate_id text;
  event_type text;
  payload jsonb;
begin
  aggregate_type := case TG_TABLE_NAME
    when 'orders' then 'order'
    when 'notifications' then 'notification'
    when 'rider_locations' then 'rider_location'
    else TG_TABLE_NAME
  end;

  aggregate_id := coalesce((to_jsonb(NEW)->>'id'), (to_jsonb(OLD)->>'id'), (to_jsonb(NEW)->>'rider_id'), (to_jsonb(OLD)->>'rider_id'));
  event_type := lower(TG_TABLE_NAME || '.' || TG_OP);
  payload := jsonb_build_object(
    'table', TG_TABLE_NAME,
    'operation', TG_OP,
    'new', case when TG_OP = 'DELETE' then null else to_jsonb(NEW) end,
    'old', case when TG_OP = 'INSERT' then null else to_jsonb(OLD) end,
    'occurred_at', now()
  );

  insert into public.setu_event_outbox(event_type, aggregate_type, aggregate_id, payload)
  values (event_type, aggregate_type, aggregate_id, payload);
  return coalesce(NEW, OLD);
end;
$$;

drop trigger if exists trg_setu_kafka_orders on public.orders;
create trigger trg_setu_kafka_orders
after insert or update or delete on public.orders
for each row execute function public.setu_enqueue_kafka_event();

drop trigger if exists trg_setu_kafka_notifications on public.notifications;
create trigger trg_setu_kafka_notifications
after insert or update or delete on public.notifications
for each row execute function public.setu_enqueue_kafka_event();

drop trigger if exists trg_setu_kafka_rider_locations on public.rider_locations;
create trigger trg_setu_kafka_rider_locations
after insert or update or delete on public.rider_locations
for each row execute function public.setu_enqueue_kafka_event();

comment on table public.setu_event_outbox is 'Transactional event outbox consumed by the SETU Kafka worker.';
