apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: setu-kafka-worker
  namespace: setu
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: setu-kafka-worker
